// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FeatherGithub: typeof import('virtual:vite-icons/feather/github')['default']
    FeatherLinkedin: typeof import('virtual:vite-icons/feather/linkedin')['default']
    FeatherMail: typeof import('virtual:vite-icons/feather/mail')['default']
    FeatherSend: typeof import('virtual:vite-icons/feather/send')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
  }
}

export { }
