// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 🏴󠁧󠁢󠁥󠁮󠁧󠁿 English
	 */
	NAME: string
	/**
	 * Manuel Quarneti's personal website
	 */
	DESCRIPTION: string
	/**
	 * 👋 Hi, I'm Manuel Quarneti
	 */
	HI: string
	/**
	 * 📄 Download my CV
	 */
	DOWNLOAD_CV: string
	/**
	 * 🗂️ Projects
	 */
	PROJECTS: string
	/**
	 * Source code
	 */
	SOURCE_CODE: string
}

export type TranslationFunctions = {
	/**
	 * 🏴󠁧󠁢󠁥󠁮󠁧󠁿 English
	 */
	NAME: () => LocalizedString
	/**
	 * Manuel Quarneti's personal website
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * 👋 Hi, I'm Manuel Quarneti
	 */
	HI: () => LocalizedString
	/**
	 * 📄 Download my CV
	 */
	DOWNLOAD_CV: () => LocalizedString
	/**
	 * 🗂️ Projects
	 */
	PROJECTS: () => LocalizedString
	/**
	 * Source code
	 */
	SOURCE_CODE: () => LocalizedString
}

export type Formatters = {}
