// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonEmail: typeof import('~icons/carbon/email')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    Header: typeof import('./components/Header.vue')['default']
  }
}

export { }
